//
// $Id$

package com.threerings.msoy.server;

import java.io.Serializable;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

import com.samskivert.util.StringUtil;

import com.threerings.panopticon.common.hessian.BaseEvent;

/**
 * Logging events generated by the Whirled server.
 */
public class MsoyEvents
{
    public static class CurrentMemberStats extends MsoyEvent
    {
        public String serverName;
        public int total;
        public int active;
        public int guests;
    }

    public static class Login extends MsoyEvent
    {
        public int memberId;
        public boolean firstLogin;
        public String sessionToken;
    }

    public static class Logout extends MsoyEvent
    {
        public int memberId;
        public String sessionToken;
        public int activeSeconds;
        public int idleSeconds;
    }

    public static class MailSent extends MsoyEvent
    {
        public int senderId;
        public int recipientId;
        public int payloadType;
    }

    public static class FlowTransaction extends MsoyEvent
    {
        public int memberId;
        public int actionType;
        public int deltaFlow;
        public int newtotal;
        public String details;
    }

    public static class ItemPurchase extends MsoyEvent
    {
        public int memberId;
        public byte itemType;
        public int itemId;
        public int flowCost;
        public int goldCost;
    }

    public static class ItemCatalogListing extends MsoyEvent
    {
        public int creatorId;
        public byte itemType;
        public int itemId;
        public int flowCost;
        public int goldCost;
        public int pricing;
        public int salesTarget;
    }

    public static class FriendshipAction extends MsoyEvent
    {
        public int memberId;
        public int friendId;
        public boolean isAdded;
    }

    public static class GroupMembershipAction extends MsoyEvent
    {
        public int memberId;
        public int groupId;
        public boolean isJoined;
    }

    public static class GroupRankModification extends MsoyEvent
    {
        public int memberId;
        public int groupId;
        public byte newRank;
    }

    public static class TrophyEarned extends MsoyEvent
    {
        public int recipientId;
        public int gameId;
        public String trophyIdent;
    }

    public static class PrizeEarned extends MsoyEvent
    {
        public int recipientId;
        public int gameId;
        public String prizeIdent;
        public byte prizeItemType;
    }

    protected static class MsoyEvent extends BaseEvent
        implements Serializable
    {
        public String getName () {
            String name = getClass().getName();
            return name.substring(name.lastIndexOf("$")+1);
        }

        public String toString () {
            return getName() + StringUtil.fieldsToString(this);
        }
    }
}
