//
// $Id$

package com.threerings.msoy.chat.data {

import com.threerings.io.ObjectInputStream;
import com.threerings.io.ObjectOutputStream;
import com.threerings.io.SimpleStreamableObject;

import com.threerings.presents.dobj.DSet;
import com.threerings.presents.dobj.DSet_Entry;

import com.threerings.msoy.data.MemberObject;
import com.threerings.msoy.data.all.MemberName;
import com.threerings.msoy.item.data.all.MediaDesc;

/**
 * Contains the name and avatar headshot of a chat channel participant.
 */
public class ChatterInfo extends SimpleStreamableObject
    implements DSet_Entry
{
    /** This member's name. */
    public var name :MemberName;

    /** This member's avatar headshot (or null for the default). */
    public var headshot :MediaDesc;

    /**
     * Creates a chatter info record for the specified member.
     */
    public function ChatterInfo (mobj :MemberObject = null)
    {
        // autogenerated: only used for unserialization
    }

    // from DSet_Entry
    public function getKey () :Object
    {
        return name;
    }

    // from interface Streamable
    override public function readObject (ins :ObjectInputStream) :void
    {
        super.readObject(ins);
        name = (ins.readObject() as MemberName);
        headshot = (ins.readObject() as MediaDesc);
    }

    // from interface Streamable
    override public function writeObject (out :ObjectOutputStream) :void
    {
        super.writeObject(out);
        out.writeObject(name);
        out.writeObject(headshot);
    }
}
}
