#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          msoy-server
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop msoy whirled server
### END INIT INFO
#
# msoy-server		This init.d script is used to start whirled msoy server.


. /lib/lsb/init-functions

test -f /etc/default/rcS && . /etc/default/rcS

msoy_stop() {
	/export/msoy/bin/msoy stop
}

msoy_start() {
	/export/msoy/bin/msoy start
}

case $1 in
	start)
		log_daemon_msg "Starting msoy server" "whirled"
		if msoy_start; then
                        log_end_msg 0
                else
                        log_end_msg 1
                fi
	;;
	stop)
		if msoy_stop; then
                        log_end_msg 0
                else
                        log_end_msg 1
                fi
	;;
	restart)
		log_daemon_msg "Restarting msoy server" "whirled"
		if ! msoy_stop; then
                        log_end_msg 1 || true
                fi
		sleep 5
		if msoy_start; then
                        log_end_msg 0
                else
                        log_end_msg 1
                fi
	;;
	*)
		log_success_msg "Usage: /etc/init.d/msoy-server {start|stop|restart}"
		exit 1
	;;
esac
